name: Fetch Substack RSS Feed
on:
  schedule:
    - cron: '0 */4 * * *'  # Runs every 4 hours (fixed syntax)
  workflow_dispatch:  # Allows manual triggering

jobs:
  fetch-rss:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4
    
    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.9'
    
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install feedparser
    
    - name: Fetch RSS Feed
      run: |
        python3 - << EOF
        import feedparser
        import json
        from datetime import datetime
        
        feed_url = "https://femmefuturescooperative.substack.com/feed"
        
        feed = feedparser.parse(feed_url)
        
        # Extract relevant article information
        articles = []
        for entry in feed.entries[:10]:  # Limit to 10 most recent articles
            # Parse the published date
            try:
                # Try parsing with different formats
                parsed_date = datetime.strptime(entry.published, "%a, %d %b %Y %H:%M:%S %z")
                formatted_date = parsed_date.strftime("%B %d, %Y")
            except:
                formatted_date = entry.published
            
            article = {
                "title": entry.title,
                "link": entry.link,
                "published": formatted_date,
                "summary": entry.summary[:300] + "..." if len(entry.summary) > 300 else entry.summary
            }
            articles.append(article)
        
        # Write to JSON file
        with open('substack-feed.json', 'w', encoding='utf-8') as f:
            json.dump(articles, f, indent=2, ensure_ascii=False)
        EOF
    
    - name: Commit and Push
      run: |
        git config user.name github-actions
        git config user.email github-actions@github.com
        git add substack-feed.json
        git commit -m "Update Substack RSS feed" || exit 0
        git push
