<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Femme Futures: Y2K Edition</title>
    <style>
        /* Your existing CSS remains the same */
    </style>
</head>
<body>
    <!-- Your existing navigation and sections remain the same -->

    <script>
        // Navigation Handler (your existing code)
        document.querySelectorAll('.nav-menu a').forEach(link => {
            link.addEventListener('click', (e) => {
                e.preventDefault();
                const pageId = e.target.getAttribute('data-page');
                
                // Hide all pages
                document.querySelectorAll('.page').forEach(page => {
                    page.classList.remove('active');
                });

                // Show selected page
                document.getElementById(pageId).classList.add('active');
            });
        });

        // RSS Feed Integration
        async function fetchSubstackRSS() {
            const homeFeedContainer = document.getElementById('rss-feed-container');
            const substackArticlesContainer = document.getElementById('substack-articles-container');
            
            try {
                // Use the GitHub Pages raw content URL for your repository
                const response = await fetch('https://raw.githubusercontent.com/[YOUR-USERNAME]/[YOUR-REPO-NAME]/main/substack-feed.json');
                const articles = await response.json();

                // Populate home page latest articles
                homeFeedContainer.innerHTML = articles.slice(0, 3).map(article => `
                    <div class="rss-article">
                        <h4><a href="${article.link}" target="_blank">${article.title}</a></h4>
                        <small>${article.published}</small>
                        <p>${article.summary}</p>
                    </div>
                `).join('');

                // Populate full blog posts page
                substackArticlesContainer.innerHTML = articles.map(article => `
                    <div class="blog-post">
                        <h3><a href="${article.link}" target="_blank">${article.title}</a></h3>
                        <div class="blog-post-date">${article.published}</div>
                        <p>${article.summary}</p>
                        <a href="${article.link}" target="_blank" style="color: var(--primary-pink)">Read More</a>
                    </div>
                `).join('');
            } catch (error) {
                console.error('RSS Feed Error:', error);
                homeFeedContainer.innerHTML = '<p>Error loading articles. Please try again later.</p>';
                substackArticlesContainer.innerHTML = '<p>Error loading articles. Please try again later.</p>';
            }
        }

        // Call RSS feed function on page load
        fetchSubstackRSS();
    </script>
</body>
</html>
