name: Fetch Substack RSS Feed

on:
  schedule:
    - cron: '0 */4 * * *'  # Runs every 4 hours
  workflow_dispatch:  # Allows manual triggering

jobs:
  fetch-rss:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
    
    - name: Set up Python
      uses: actions/setup-python@v3
      with:
        python-version: '3.9'
    
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install feedparser
    
    - name: Fetch RSS Feed
      run: |
        python - << EOF
        import feedparser
        import json
        
        feed_url = "https://femmefuturescooperative.substack.com/feed"
        
        feed = feedparser.parse(feed_url)
        
        # Extract relevant article information
        articles = []
        for entry in feed.entries[:10]:  # Limit to 10 most recent articles
            article = {
                "title": entry.title,
                "link": entry.link,
                "published": entry.published,
                "summary": entry.summary
            }
            articles.append(article)
        
        # Write to JSON file
        with open('substack-feed.json', 'w') as f:
            json.dump(articles, f, indent=2)
        EOF
    
    - name: Commit and Push
      run: |
        git config user.name github-actions
        git config user.email github-actions@github.com
        git add substack-feed.json
        git commit -m "Update Substack RSS feed" || exit 0
        git push
